subscription_id      = "51199e9b-8fa9-4269-825e-fa5d7cc2b857"
location             = "uksouth"
prefix               = "s255d02"
tag_environment      = "Dev"
tag_product          = "Calculate Funding Service (CFS)"
tag_service_offering = "Calculate Funding Service (CFS)"