// <auto-generated />
//
// To parse this JSON data, add NuGet 'System.Text.Json' then do:
//
//    using CommunicationsAlpha2025.Versions.V2.Models.Calculations;
//
//    var calculationResults = CalculationResults.FromJson(jsonString);
//    
//    Note: Code generated from anonymised JSON, using https://app.quicktype.io/
#nullable enable
#pragma warning disable CS8618
#pragma warning disable CS8601
#pragma warning disable CS8603

namespace CommunicationsAlpha2025.Versions.V2.Models.Calculations
{
    using System;
    using System.Collections.Generic;

    using System.Text.Json;
    using System.Text.Json.Serialization;
    using System.Globalization;

    public partial class CalculationResults
    {
        [JsonPropertyName("specification")]
        public Specification Specification { get; set; }

        [JsonPropertyName("provider")]
        public Provider Provider { get; set; }

        [JsonPropertyName("fundingTemplate")]
        public FundingTemplate FundingTemplate { get; set; }
    }

    public partial class FundingTemplate
    {
        [JsonPropertyName("fundingLines")]
        public List<FundingLine> FundingLines { get; set; }
    }

    public partial class FundingLine
    {
        [JsonPropertyName("templateLineId")]
        public long TemplateLineId { get; set; }

        [JsonPropertyName("type")]
        public string Type { get; set; }

        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("fundingLineCode")]
        public string FundingLineCode { get; set; }

        [JsonPropertyName("fundingLines")]
        public List<object> FundingLines { get; set; }

        [JsonPropertyName("value")]
        public long Value { get; set; }

        [JsonPropertyName("calculations")]
        public List<Calculation> Calculations { get; set; }
    }

    public partial class Calculation
    {
        [JsonPropertyName("templateCalculationId")]
        public long TemplateCalculationId { get; set; }

        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("type")]
        public string Type { get; set; }

        [JsonPropertyName("aggregationType")]
        public string AggregationType { get; set; }

        [JsonPropertyName("formulaText")]
        public string FormulaText { get; set; }

        [JsonPropertyName("valueFormat")]
        public string ValueFormat { get; set; }

        [JsonPropertyName("value")]
        public long? Value { get; set; }

        [JsonPropertyName("calculations")]
        public List<Calculation> Calculations { get; set; }
    }

    public partial class Provider
    {
        [JsonPropertyName("urn")]
        public string Urn { get; set; }

        [JsonPropertyName("ukPrn")]
        public string UkPrn { get; set; }

        [JsonPropertyName("id")]
        public string Id { get; set; }

        [JsonPropertyName("name")]
        public string Name { get; set; }
    }

    public partial class Specification
    {
        [JsonPropertyName("name")]
        public string Name { get; set; }

        [JsonPropertyName("specificationId")]
        public Guid SpecificationId { get; set; }

        [JsonPropertyName("fundingPeriod")]
        public Funding FundingPeriod { get; set; }

        [JsonPropertyName("fundingStreams")]
        public List<Funding> FundingStreams { get; set; }
    }

    public partial class Funding
    {
        [JsonPropertyName("id")]
        public string Id { get; set; }

        [JsonPropertyName("name")]
        public string Name { get; set; }
    }

    public partial class CalculationResults
    {
        public static CalculationResults FromJson(string json) =>
            JsonSerializer.Deserialize<CalculationResults>(json, CommunicationsAlpha2025.Versions.V2.Models.Calculations.Converter.Settings);

        public static List<CalculationResults> FromJsonElement(IEnumerable<JsonElement> elements)
        {
            var results = new List<CalculationResults>();

            foreach (var element in elements)
            {
                var item = JsonSerializer.Deserialize<CalculationResults>(
                    element,
                    CommunicationsAlpha2025.Versions.V2.Models.Calculations.Converter.Settings
                );

                if (item != null)
                {
                    results.Add(item);
                }
            }

            return results;
        }
    }

    public static class Serialize
    {
        public static string ToJson(this CalculationResults self) => JsonSerializer.Serialize(self, CommunicationsAlpha2025.Versions.V2.Models.Calculations.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerOptions Settings = new(JsonSerializerDefaults.General)
        {
            Converters =
            {
                new DateOnlyConverter(),
                new TimeOnlyConverter(),
                IsoDateTimeOffsetConverter.Singleton
            },
        };
    }

    public class DateOnlyConverter : JsonConverter<DateOnly>
    {
        private readonly string serializationFormat;
        public DateOnlyConverter() : this(null) { }

        public DateOnlyConverter(string? serializationFormat)
        {
            this.serializationFormat = serializationFormat ?? "yyyy-MM-dd";
        }

        public override DateOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            return DateOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, DateOnly value, JsonSerializerOptions options)
                => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    public class TimeOnlyConverter : JsonConverter<TimeOnly>
    {
        private readonly string serializationFormat;

        public TimeOnlyConverter() : this(null) { }

        public TimeOnlyConverter(string? serializationFormat)
        {
            this.serializationFormat = serializationFormat ?? "HH:mm:ss.fff";
        }

        public override TimeOnly Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            var value = reader.GetString();
            return TimeOnly.Parse(value!);
        }

        public override void Write(Utf8JsonWriter writer, TimeOnly value, JsonSerializerOptions options)
                => writer.WriteStringValue(value.ToString(serializationFormat));
    }

    internal class IsoDateTimeOffsetConverter : JsonConverter<DateTimeOffset>
    {
        public override bool CanConvert(Type t) => t == typeof(DateTimeOffset);

        private const string DefaultDateTimeFormat = "yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK";

        private DateTimeStyles _dateTimeStyles = DateTimeStyles.RoundtripKind;
        private string? _dateTimeFormat;
        private CultureInfo? _culture;

        public DateTimeStyles DateTimeStyles
        {
            get => _dateTimeStyles;
            set => _dateTimeStyles = value;
        }

        public string? DateTimeFormat
        {
            get => _dateTimeFormat ?? string.Empty;
            set => _dateTimeFormat = (string.IsNullOrEmpty(value)) ? null : value;
        }

        public CultureInfo Culture
        {
            get => _culture ?? CultureInfo.CurrentCulture;
            set => _culture = value;
        }

        public override void Write(Utf8JsonWriter writer, DateTimeOffset value, JsonSerializerOptions options)
        {
            string text;


            if ((_dateTimeStyles & DateTimeStyles.AdjustToUniversal) == DateTimeStyles.AdjustToUniversal
                    || (_dateTimeStyles & DateTimeStyles.AssumeUniversal) == DateTimeStyles.AssumeUniversal)
            {
                value = value.ToUniversalTime();
            }

            text = value.ToString(_dateTimeFormat ?? DefaultDateTimeFormat, Culture);

            writer.WriteStringValue(text);
        }

        public override DateTimeOffset Read(ref Utf8JsonReader reader, Type typeToConvert, JsonSerializerOptions options)
        {
            string? dateText = reader.GetString();

            if (string.IsNullOrEmpty(dateText) == false)
            {
                if (!string.IsNullOrEmpty(_dateTimeFormat))
                {
                    return DateTimeOffset.ParseExact(dateText, _dateTimeFormat, Culture, _dateTimeStyles);
                }
                else
                {
                    return DateTimeOffset.Parse(dateText, Culture, _dateTimeStyles);
                }
            }
            else
            {
                return default(DateTimeOffset);
            }
        }


        public static readonly IsoDateTimeOffsetConverter Singleton = new IsoDateTimeOffsetConverter();
    }
}
#pragma warning restore CS8618
#pragma warning restore CS8601
#pragma warning restore CS8603
