// <auto-generated />
using CommunicationsAlpha2025.Versions.V2.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CommunicationsAlpha2025.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260323160907_Relational table added")]
    partial class Relationaltableadded
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CommunicationsAlpha2025.Versions.V2.Data.Models.FundingStream", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SpecificationId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SpecificationId");

                    b.ToTable("fundingStreams", "calc");
                });

            modelBuilder.Entity("CommunicationsAlpha2025.Versions.V2.Data.Models.Specification_GQL", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SpecificationId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Specifications", "calc");
                });

            modelBuilder.Entity("CommunicationsAlpha2025.Versions.V2.Data.Models.FundingStream", b =>
                {
                    b.HasOne("CommunicationsAlpha2025.Versions.V2.Data.Models.Specification_GQL", "Specification")
                        .WithMany("FundingStreams")
                        .HasForeignKey("SpecificationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Specification");
                });

            modelBuilder.Entity("CommunicationsAlpha2025.Versions.V2.Data.Models.Specification_GQL", b =>
                {
                    b.Navigation("FundingStreams");
                });
#pragma warning restore 612, 618
        }
    }
}
